import torch

IMG_PATCH_SIZE = 64
STANDARD_PATCH_SIZE = 16

UNet_OVERLAP = 16
UNet_PATCH_SIZE = 80

TEST_IMG_SIZE = 608
TEST_PATCHES_PER_IMG = 38
NBR_TEST_IMAGES = 50

FOREGROUND_THRESHOLD = 0.25
P_THRESHOLD = 0.5

if torch.cuda.is_available():
    NUM_WORKERS = 2
else:
    NUM_WORKERS = 0